//Client file generated by RPC Compiler.
import { Injectable } from '@angular/core';
import { Http, Response } from '@angular/http';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/catch';
import {Converter} from './rpc';
import {Dog} from "../app/dog";
import {rpcService, rpcMember} from './rpc';export class Demo {
	constructor(private $_Angular2HttpClient: Http){
	}
	public Dogs(): Observable< Dog[]>{
		return this.$_Angular2HttpClient.post('/rpc/demo.cgi.js?Demo-Dogs', []).map(Converter.convertJsonResponse);
	}
	public test(jack: string, sam:  number, jason:  Dog): Observable< string>{
		return this.$_Angular2HttpClient.post('/rpc/demo.cgi.js?Demo-test', [jack, sam, jason]).map(Converter.convertStringResponse);
	}
	public tom(): Observable< Dog>{
		return this.$_Angular2HttpClient.post('/rpc/demo.cgi.js?Demo-tom', []).map(Converter.convertJsonResponse);
	}
	public jerry(): Observable< boolean>{
		return this.$_Angular2HttpClient.post('/rpc/demo.cgi.js?Demo-jerry', []).map(Converter.convertBooleanResponse);
	}
}
